title: Raelog
description: "Field notes. Observations. Markers."
markdown: kramdown
timezone: America/Los_Angeles
future: true


baseurl: ""
url: "https://raelog.net"

permalink: /:title/

exclude:
  - README.md
