title: Raelog
description: "Field notes. Observations. Markers."
markdown: kramdown

baseurl: "/raelog"
url: "https://raelovejoy.github.io"

permalink: /:year-:month-:day-:title/

exclude:
  - README.md
